### ISSUE TITLE
Converions to F seems wrong

### ISSUE THREAD

**Issue by ve3sjk** [DFRobot/DFRobot_SHT3x#1]
I am converting a program from using the Arduino library for SHT35 sensor to this one but i noticed that the F values are not correct.

From Arduino Lib
<
SHT:
  RH   :   74.69
  T (c): 21.25
  T (f): 70.25
SHT:
  RH   :   74.66
  T (c): 21.26
  T (f): 70.28
SHT:
  RH   :   74.65
  T (c): 21.22
  T (f): 70.20
SHT:
  RH   :   74.64
  T (c): 21.21
>
From Single Measurement Sample using addr 44

<------------------Read adta in single measurement mode-----------------------
Ambient Temperature(°C/F):21.28 C/53.25 F Relative Humidity(%RH):74.57 %RH
Ambient Temperature(°C/F):21.28 C/53.28 F Relative Humidity(%RH):74.55 %RH
Ambient Temperature(°C/F):21.28 C/53.28 F Relative Humidity(%RH):74.52 %RH
Ambient Temperature(°C/F):21.29 C/53.29 F Relative Humidity(%RH):74.52 %RH
Ambient Temperature(°C/F):21.28 C/53.29 F Relative Humidity(%RH):74.49 %RH
Ambient Temperature(°C/F):21.29 C/53.31 F Relative Humidity(%RH):74.50 %RH
Ambient Temperature(°C/F):21.28 C/53.29 F Relative Humidity(%RH):74.50 %RH
>

**Comment by ocouch** [comment]
It is wrong! The issue is integer math (9/5 =1) instead of float math (9.0/5.0 = 1.8) I made a pull request to fix this: #6 

Though I just noticed someone else has made a similar patch (though not as neat, if I do say so myself ;) ): #2
