### ISSUE TITLE
note on compile

### ISSUE THREAD

**Issue by RomanSmajla** [DFRobot/DFRobot_SHT3x#5]
When compile in Visual Studio for ESP32 I get this note:
DFRobot_SHT3x.h:99: note  offset of packed bit-field DFRobot_SHT3x  <anonymous struct>  reserved1 has changed in GCC 4.4
   typedef struct {
esptool.py v3.0-dev

this part of code is something wrong in DFRobot_SHT3x.h

 typedef struct {
    uint8_t writeDataChecksumStatus : 1;
    uint8_t commandStatus : 1;
    uint8_t reserved0 : 2;
    uint8_t systemResetDeteced : 1;
    uint8_t reserved1 : 5;
    uint8_t temperatureAlert : 1;
    uint8_t humidityAlert : 1;
    uint8_t reserved2 : 1;
    uint8_t heaterStaus :1;
    uint8_t reserved3 :1;
    uint8_t alertPendingStatus :1;
  }__attribute__ ((packed)) sStatusRegister_t;

Compiling is OK but need to something change in library

Best regards

**Comment by pleasetakeup** [comment]
Thank you for your question. We have modified the code to eliminate this warning
