### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission()

### ISSUE THREAD

**Issue by Koepel** [DFRobot/DFRobot_SHT3x#7]
In the file "DFRobot_SHT3x.cpp", in the function "readData()", there is a `_pWire->endTransmission()` after a `_pWire->requestFrom()`.
That `_pWire->endTransmission()` can be removed.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by pleasetakeup** [comment]
Yeah, This is useless code, and we'll get rid of it
