### ISSUE TITLE
Clock streching register cmd xith polling read method

### ISSUE THREAD

**Issue by mafabrique** [DFRobot/DFRobot_SHT3x#8]
Dear,
in your lib your are using clockstreching register to read data but your are using polling method to read byte data so in this way the sck pin of the sht3w be low and in some case it can block the i2c bus because sck  is in low state... Sometimes the sht3x never pullup the sck pin.
so maybe it can be better to use polling register to read in polling mode than use mixed method.

//clock streching
#define SHT3X_CMD_GETDATA_H_CLOCKENBLED          (0x2C06)// Measurement:high repeatability
#define SHT3X_CMD_GETDATA_M_CLOCKENBLED          (0x2C0D)// Measurement: medium repeatability
#define SHT3X_CMD_GETDATA_L_CLOCKENBLED          (0x2C10)// Measurement: low repeatability
//polling
#define SHT3X_CMD_GETDATA_POLLING_H   (0x2400) // measurement: polling, high repeatability
#define SHT3X_CMD_GETDATA_POLLING_M   (0x240B) // measurement: polling, medium repeatability
#define SHT3X_CMD_GETDATA_POLLING_L   (0x2416) // measurement: polling, low repeatability

//Actual method
DFRobot_SHT3x::sRHAndTemp_t DFRobot_SHT3x::readTemperatureAndHumidity(eRepeatability_t repeatability)
{
  uint8_t rawData[6];
  uint8_t rawTemperature[3];
  uint8_t rawHumidity[3];
  tempRH.ERR = 0;
  switch (repeatability)
  {
  case eRepeatability_High:
    writeCommand(SHT3X_CMD_GETDATA_H_CLOCKENBLED, 2);
    break;
  case eRepeatability_Medium:
    writeCommand(SHT3X_CMD_GETDATA_M_CLOCKENBLED, 2);
    break;
  case eRepeatability_Low:
    writeCommand(SHT3X_CMD_GETDATA_L_CLOCKENBLED, 2);
    break;
  }
  delay(15); //wait polling method sck state not tested  !!
  readData(rawData, 6);
  memcpy(rawTemperature, rawData, 3);
  memcpy(rawHumidity, rawData + 3, 3);
  if ((checkCrc(rawTemperature) != rawTemperature[2]) || (checkCrc(rawHumidity) != rawHumidity[2]))
  {
    tempRH.ERR = -1;
    return tempRH;
  }
  tempRH.TemperatureC = convertTemperature(rawTemperature);
  tempRH.TemperatureF = (9 / 5) * tempRH.TemperatureC + 32;
  tempRH.Humidity = convertHumidity(rawHumidity);
  return tempRH;
}

**Comment by pleasetakeup** [comment]
Thanks for your suggestion, we have modified the code and tested it

**Comment by mafabrique** [comment]
Thanks to you for this good lib !
